language: python
python:
  - "3.5"
  - "3.6"
addons:
  apt_packages:
    - pandoc
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source ./enforce -m unittest discover ./tests
after_success:
  - coveralls